### ISSUE TITLE
Wire Frame_Xiayan

### ISSUE THREAD

**Issue by emilywang2020** [CSI-3471-project/CSI-3471#10]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by TinaXiayanLi** [comment]
made the main windows outlook

**Comment by TinaXiayanLi** [comment]
made the main window look

**Comment by TinaXiayanLi** [comment]
made the 3 request windows: need item post, bid item post, sell item post

**Comment by TinaXiayanLi** [comment]
made 4 fill-in information windows: need item form, make bid form, sell item form and place a bid form

**Comment by TinaXiayanLi** [comment]
made the chat window

**Comment by TinaXiayanLi** [comment]
finish out looking
![image-20201001-001001-b4b06d44](https://user-images.githubusercontent.com/44931077/94756430-230f9e00-035d-11eb-9eb6-ecaefcc99485.jpg)
