### ISSUE TITLE
Operation Contract

### ISSUE THREAD

**Issue by emilywang2020** [CSI-3471-project/CSI-3471#15]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by TinaXiayanLi** [comment]
update createRequestPost, giveInfo, changePost, reInputPrice and consentPost for need item post

**Comment by TinaXiayanLi** [comment]
update gradeTrade, doesReport for evaluation

**Comment by TinaXiayanLi** [comment]
update enterBiddingPrice for bidding
