### ISSUE TITLE
System Operations

### ISSUE THREAD

**Issue by emilywang2020** [CSI-3471-project/CSI-3471#19]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by TinaXiayanLi** [comment]
update createRequestPost, giveInfo, changePost, reInputPrice, consentPost for need item post use case

**Comment by TinaXiayanLi** [comment]
update gradeTrade, doesReport for evaluation use case

**Comment by TinaXiayanLi** [comment]
update enterBiddingPrice for bidding use case
